In [270]:
using Oscar

In [271]:
function nulla(polys,K)
d = maximum([total_degree(poly) for poly in polys])
while d <= K
    cert = sum()
end
end

nulla (generic function with 1 method)

In [272]:
R, x = PolynomialRing(QQ, ["x$i" for i in 1:3])

(Multivariate Polynomial Ring in x1, x2, x3 over Rational Field, fmpq_mpoly[x1, x2, x3])

In [273]:
f1 = x[1]^2 - 1
f2 = x[1] + x[2]
f3 = x[1] + x[3]
f4 = x[2] + x[3]
listap = [f1,f2,f3,f4]

4-element Vector{fmpq_mpoly}:
 x1^2 - 1
 x1 + x2
 x1 + x3
 x2 + x3

In [274]:
T, y =  PolynomialRing(R,["y$i" for i in 1:4])

(Multivariate Polynomial Ring in y1, y2, y3, y4 over Multivariate Polynomial Ring in x1, x2, x3 over Rational Field, AbstractAlgebra.Generic.MPoly{fmpq_mpoly}[y1, y2, y3, y4])

In [275]:
fg=y[1]*x[1]

x1*y1

In [276]:
d = maximum([total_degree(poly) for poly in listap])
for f in listap
    deg = d - total_degree(f)
    
    for 
        b = sum()
    end
end

MethodError: MethodError: no method matching sum()
Closest candidates are:
  sum(!Matched::ChainRulesCore.AbstractZero; dims) at ~/.julia/packages/ChainRulesCore/a4mIA/src/tangent_types/abstract_zero.jl:40
  sum(!Matched::ChainRulesCore.AbstractThunk; kws...) at ~/.julia/packages/ChainRulesCore/a4mIA/src/tangent_types/thunks.jl:53
  sum(!Matched::AbstractAlgebra.Generic.Partition) at ~/.julia/packages/AbstractAlgebra/FcxWh/src/generic/YoungTabs.jl:29
  ...

In [277]:
function partition(n::Int, d::Int)
    if n == 1
        return [[d]]
    end
    partitions = []
    for i in 0:d
        for p in partition(n-1, d-i)
            push!(partitions, [i; p])
        end
    end
    return partitions
end


partition (generic function with 1 method)

In [279]:
partition(2,3)

4-element Vector{Any}:
 [0, 3]
 [1, 2]
 [2, 1]
 [3, 0]

In [280]:
partition(2,2)

3-element Vector{Any}:
 [0, 2]
 [1, 1]
 [2, 0]

In [281]:
partition(2,1)

2-element Vector{Any}:
 [0, 1]
 [1, 0]

In [282]:
partition(2,0)

1-element Vector{Any}:
 [0, 0]

In [283]:
[reduce(*,[x[i]^par[i] for i in 1:length(par)]) for par in partition(3,3)]

10-element Vector{fmpq_mpoly}:
 x3^3
 x2*x3^2
 x2^2*x3
 x2^3
 x1*x3^2
 x1*x2*x3
 x1*x2^2
 x1^2*x3
 x1^2*x2
 x1^3

In [284]:
nn = sum([length(partition(3,i)) for i in 0:3]) * length(listap)

80

In [285]:
T, y =  PolynomialRing(R,["y$i" for i in 1:nn])

(Multivariate Polynomial Ring in 80 variables y1, y2, y3, y4, ..., y80 over Multivariate Polynomial Ring in x1, x2, x3 over Rational Field, AbstractAlgebra.Generic.MPoly{fmpq_mpoly}[y1, y2, y3, y4, y5, y6, y7, y8, y9, y10  …  y71, y72, y73, y74, y75, y76, y77, y78, y79, y80])

In [286]:
[reduce(*,[x[i]^par[i] for i in 1:length(par)]) for par in partition(3,2)]

6-element Vector{fmpq_mpoly}:
 x3^2
 x2*x3
 x2^2
 x1*x3
 x1*x2
 x1^2

In [287]:
[reduce(*,[x[i]^par[i] for i in 1:length(par)]) for par in partition(3,1)]

3-element Vector{fmpq_mpoly}:
 x3
 x2
 x1

In [288]:
function polysFi(n::Int, d::Int)
    v = []
    for j in 0:d
        v = vcat(v, [reduce(*,[x[i]^par[i] for i in 1:length(par)]) for par in partition(n,j)])
    end
    return v
end

polysFi (generic function with 1 method)

In [289]:
polysFi(3,5)

56-element Vector{Any}:
 1
 x3
 x2
 x1
 x3^2
 x2*x3
 x2^2
 x1*x3
 x1*x2
 x1^2
 ⋮
 x1^2*x2*x3^2
 x1^2*x2^2*x3
 x1^2*x2^3
 x1^3*x3^2
 x1^3*x2*x3
 x1^3*x2^2
 x1^4*x3
 x1^4*x2
 x1^5

In [290]:
f= x[1]
parent(f)

Multivariate Polynomial Ring in x1, x2, x3 over Rational Field

In [291]:
function creaCertv(d,listap)
    v=[]
    n=length(gens(parent(listap[1])))
    for f in listap
        dd = total_degree(f)
        v = vcat(v,[ f * bi for bi in polysFi(n, d - dd)])
    end
    return v
end

creaCertv (generic function with 1 method)

In [292]:
d = maximum([total_degree(poly) for poly in listap])
bifi = creaCertv(d,listap)

13-element Vector{Any}:
 x1^2 - 1
 x1 + x2
 x1*x3 + x2*x3
 x1*x2 + x2^2
 x1^2 + x1*x2
 x1 + x3
 x1*x3 + x3^2
 x1*x2 + x2*x3
 x1^2 + x1*x3
 x2 + x3
 x2*x3 + x3^2
 x2^2 + x2*x3
 x1*x2 + x1*x3

In [293]:
nUnkows = length(bifi)
T, y =  PolynomialRing(R,["y$i" for i in 1:nUnkows])
R2, z = PolynomialRing(T,["z$i" for i in 1:3])

(Multivariate Polynomial Ring in z1, z2, z3 over Multivariate Polynomial Ring in 13 variables y1, y2, y3, y4, ..., y13 over Multivariate Polynomial Ring in x1, x2, x3 over Rational Field, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.MPoly{fmpq_mpoly}}[z1, z2, z3])

In [294]:
evaluate(bifi[1],collect(gens(R2)))

z1^2 - 1

In [295]:
bifi2 = [evaluate(bf,collect(gens(R2))) for bf in bifi]

13-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.MPoly{fmpq_mpoly}}}:
 z1^2 - 1
 z1 + z2
 z1*z3 + z2*z3
 z1*z2 + z2^2
 z1^2 + z1*z2
 z1 + z3
 z1*z3 + z3^2
 z1*z2 + z2*z3
 z1^2 + z1*z3
 z2 + z3
 z2*z3 + z3^2
 z2^2 + z2*z3
 z1*z2 + z1*z3

In [297]:
certv = [ y[i]*bifi2[i] for i in  1:length(bifi2)]

13-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.MPoly{fmpq_mpoly}}}:
 y1*z1^2 - y1
 y2*z1 + y2*z2
 y3*z1*z3 + y3*z2*z3
 y4*z1*z2 + y4*z2^2
 y5*z1^2 + y5*z1*z2
 y6*z1 + y6*z3
 y7*z1*z3 + y7*z3^2
 y8*z1*z2 + y8*z2*z3
 y9*z1^2 + y9*z1*z3
 y10*z2 + y10*z3
 y11*z2*z3 + y11*z3^2
 y12*z2^2 + y12*z2*z3
 y13*z1*z2 + y13*z1*z3

In [298]:
sumaa=sum(certv)

(y1 + y5 + y9)*z1^2 + (y4 + y5 + y8 + y13)*z1*z2 + (y3 + y7 + y9 + y13)*z1*z3 + (y2 + y6)*z1 + (y4 + y12)*z2^2 + (y3 + y8 + y11 + y12)*z2*z3 + (y2 + y10)*z2 + (y7 + y11)*z3^2 + (y6 + y10)*z3 - y1

In [299]:
certt = collect(terms(sumaa))

10-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.MPoly{fmpq_mpoly}}}:
 (y1 + y5 + y9)*z1^2
 (y4 + y5 + y8 + y13)*z1*z2
 (y4 + y12)*z2^2
 (y3 + y7 + y9 + y13)*z1*z3
 (y3 + y8 + y11 + y12)*z2*z3
 (y7 + y11)*z3^2
 (y2 + y6)*z1
 (y2 + y10)*z2
 (y6 + y10)*z3
 -y1

In [300]:
ccc=collect(coeffs(certt[3]))
lolo = vec([evaluate( coeff(cc, yi),[0,0,0]) for yi in gens(T), cc in ccc])
parent(lolo[1])

Rational Field

In [301]:
a = [a]
isempty(a)

false

In [302]:
A = []
for cee in certt
    achiquita = vec([convert(Rational{BigInt},(evaluate( coeff(cc, yi),zeros(Int, 3)))) for yi in gens(T), cc in collect(coeffs(cee))])
    if isempty(A)
        A = achiquita
    else
        A=hcat(A,achiquita)
    end
end
A = transpose( A)

10×13 transpose(::Matrix{Rational{BigInt}}) with eltype Rational{BigInt}:
  1//1  0//1  0//1  0//1  1//1  0//1  …  0//1  1//1  0//1  0//1  0//1  0//1
  0//1  0//1  0//1  1//1  1//1  0//1     1//1  0//1  0//1  0//1  0//1  1//1
  0//1  0//1  0//1  1//1  0//1  0//1     0//1  0//1  0//1  0//1  1//1  0//1
  0//1  0//1  1//1  0//1  0//1  0//1     0//1  1//1  0//1  0//1  0//1  1//1
  0//1  0//1  1//1  0//1  0//1  0//1     1//1  0//1  0//1  1//1  1//1  0//1
  0//1  0//1  0//1  0//1  0//1  0//1  …  0//1  0//1  0//1  1//1  0//1  0//1
  0//1  1//1  0//1  0//1  0//1  1//1     0//1  0//1  0//1  0//1  0//1  0//1
  0//1  1//1  0//1  0//1  0//1  0//1     0//1  0//1  1//1  0//1  0//1  0//1
  0//1  0//1  0//1  0//1  0//1  1//1     0//1  0//1  1//1  0//1  0//1  0//1
 -1//1  0//1  0//1  0//1  0//1  0//1     0//1  0//1  0//1  0//1  0//1  0//1

In [303]:
zeros(Int, 3)


3-element Vector{Int64}:
 0
 0
 0

In [304]:
[0,0,0]

3-element Vector{Int64}:
 0
 0
 0

In [306]:
A[1,1]

1//1

In [307]:

ceroo = zeros(length(certt))
ceroo[end]+=1
ceroo


10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

In [308]:
B =

ErrorException: syntax: incomplete: premature end of input

In [309]:
sol = A \ ceroo

13-element Vector{BigFloat}:
 -1.0
  5.346740781574805988618151613253297149417830226944220263575462452126653734729368e-81
 -0.09999999999999999999999999999999999999999999999999999999999999999999999999999482
 -0.1000000000000000000000000000000000000000000000000000000000000000000000000000013
  0.4999999999999999999999999999999999999999999999999999999999999999999999999999914
  2.697743194397055811856300959783095251880228615431768369538829726678559206655872e-79
 -0.1000000000000000000000000000000000000000000000000000000000000000000000000000002
 -0.1000000000000000000000000000000000000000000000000000000000000000000000000000056
  0.5000000000000000000000000000000000000000000000000000000000000000000000000000086
 -2.804678010028551931628663992048161194868585219970652774810338975721092281350455e-79
  0.09999999999999999999999999999999999999999999999999999999999999999999999999999698
  0.1000000000000000000000000000000000000000000000000000000000000000000000000000142
 -0.30000000000000000000000000

In [310]:
bifi2

13-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.MPoly{fmpq_mpoly}}}:
 z1^2 - 1
 z1 + z2
 z1*z3 + z2*z3
 z1*z2 + z2^2
 z1^2 + z1*z2
 z1 + z3
 z1*z3 + z3^2
 z1*z2 + z2*z3
 z1^2 + z1*z3
 z2 + z3
 z2*z3 + z3^2
 z2^2 + z2*z3
 z1*z2 + z1*z3

In [311]:
convert(Rational{BigInt}, fmpq(1))

1//1

In [312]:
[bifi2[i] * fmpq(sol[i] for i in 1: length(bifi2)]

ErrorException: syntax: unexpected "]"

In [313]:
A

10×13 transpose(::Matrix{Rational{BigInt}}) with eltype Rational{BigInt}:
  1//1  0//1  0//1  0//1  1//1  0//1  …  0//1  1//1  0//1  0//1  0//1  0//1
  0//1  0//1  0//1  1//1  1//1  0//1     1//1  0//1  0//1  0//1  0//1  1//1
  0//1  0//1  0//1  1//1  0//1  0//1     0//1  0//1  0//1  0//1  1//1  0//1
  0//1  0//1  1//1  0//1  0//1  0//1     0//1  1//1  0//1  0//1  0//1  1//1
  0//1  0//1  1//1  0//1  0//1  0//1     1//1  0//1  0//1  1//1  1//1  0//1
  0//1  0//1  0//1  0//1  0//1  0//1  …  0//1  0//1  0//1  1//1  0//1  0//1
  0//1  1//1  0//1  0//1  0//1  1//1     0//1  0//1  0//1  0//1  0//1  0//1
  0//1  1//1  0//1  0//1  0//1  0//1     0//1  0//1  1//1  0//1  0//1  0//1
  0//1  0//1  0//1  0//1  0//1  1//1     0//1  0//1  1//1  0//1  0//1  0//1
 -1//1  0//1  0//1  0//1  0//1  0//1     0//1  0//1  0//1  0//1  0//1  0//1